# Урок 3

## Матрицы и матричные операции. Часть 1

### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

#### а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

Для вычисления произведения матриц, необходимо чтобы число столюцов первой матрицы равнялось числу строк второй. В данном случае перемножение невозможно.

#### б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

В данном случае перемножение невозможно.

#### в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

Возможно произведение $AB$ и $BА$, размерность будет соответственно $8\times 8$ и $3\times 3$.

#### г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Возможны произведения $AB$ и $BA$, размерность матриц будет $4\times 4$.  

### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B =\begin{pmatrix}
(1+4) & (-2-1)\\ 
(3+0) & (0+5)
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ <br>

$A\cdot B=\begin{pmatrix}
(1\cdot4+(-2)\cdot0) & (1\cdot(-1)+(-2)\cdot5)\\ 
(3\cdot4+0\cdot0) & (3\cdot(-1)+0\cdot5)
\end{pmatrix} = \begin{pmatrix}
(4+0) & (-1-10)\\ 
(12+0) & (-3+0)
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix} $ <br>

$B\cdot A=\begin{pmatrix}
(4\cdot1+(-1)\cdot3) & (4\cdot(-2)+(-1)\cdot0)\\ 
(0\cdot1+5\cdot3) & (0\cdot(-2)+5\cdot0)
\end{pmatrix} = \begin{pmatrix}
(4-3) & (-8+0)\\ 
(0+15) & (0+0)
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix} $

In [5]:
import numpy as np

In [2]:
A = np.array([[1, -2],
              [3, 0]])
B = np.array([[4, -1],
              [0, 5]])
print(f'А+B =\n{A+B}\n')
print(f'A*B =\n{np.dot(A, B)}\n')
print(f'B*A =\n{np.dot(B, A)}')

А+B =
[[ 5 -3]
 [ 3  5]]

A*B =
[[  4 -11]
 [ 12  -3]]

B*A =
[[ 1 -8]
 [15  0]]


### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+ 4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}+ \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
A = np.array([[1, 7],
              [3, -6]])
B = np.array([[0, 5],
              [2, -1]])
C = np.array([[2, -4],
              [1, 1]])

print(f'3А-2B+4C =\n{3*A-2*B+4*C}')

3А-2B+4C =
[[ 11  -5]
 [  9 -12]]


### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix}$ <br>

$A \cdot A^{T}=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix} 
= \begin{pmatrix}
(4\cdot4+1\cdot1) & (4\cdot5+1\cdot(-2)) & (4\cdot2+1\cdot3)\\ 
(5\cdot4+(-2)\cdot1) & (5\cdot5+(-2)\cdot(-2)) & (5\cdot2+(-2)\cdot3)\\ 
(2\cdot4+3\cdot1) & (2\cdot5+3\cdot(-2)) & (2\cdot2+3\cdot3)\end{pmatrix} 
= \begin{pmatrix}
(16+1) & (20-2) & (8+3)\\ 
(20-2) & (25+4) & (10-6)\\ 
(8+3) & (10-6) & (4+9)\end{pmatrix}
= \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\end{pmatrix}$ <br>

$A^{T}\cdot A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix}\cdot
\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3\end{pmatrix}
= \begin{pmatrix}
(4\cdot4+5\cdot5+2\cdot2) & (4\cdot1+5\cdot(-2)+2\cdot3)\\ 
(1\cdot4+(-2)\cdot5+3\cdot2) & (1\cdot1+(-2)\cdot(-2)+3\cdot3)\end{pmatrix} 
= \begin{pmatrix}
(16+25+4) & (4-10+6)\\ 
(4-10+6) & (1+4+9))\end{pmatrix}
= \begin{pmatrix}
45 & 0\\ 
0 & 14\end{pmatrix}$

In [4]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])

print(f'A*A^T=\n{np.dot(A, A.T)}\n')
print(f'A^T*A=\n{np.dot(A.T, A)}')

A*A^T=
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A^T*A=
[[45  0]
 [ 0 14]]


### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [19]:
def mult(A, B):
    if A.shape[0]==B.shape[1]:
        #C = np.zeros((A.shape[0],A.shape[0]))
        C = np.array([[0.] * A.shape[0]] * A.shape[0])

        for i in range(A.shape[0]):
            for m in range(A.shape[0]):
                for n in range(A.shape[1]):
                    C[i, m] += A[i,n]*B[n,m]
    return C       

In [20]:
A = np.array([[1, -2],
              [3, 0]])
B = np.array([[4, -1],
              [0, 5]])

print(f'A*B =\n{mult(A, B)}\n')
print(f'B*A =\n{mult(B, A)}')

A*B =
[[  4. -11.]
 [ 12.  -3.]]

B*A =
[[ 1. -8.]
 [15.  0.]]


In [21]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])

B = A.T

print(f'A*B =\n{mult(A, B)}\n')
print(f'B*A =\n{mult(B, A)}')

A*B =
[[17. 18. 11.]
 [18. 29.  4.]
 [11.  4. 13.]]

B*A =
[[45.  0.]
 [ 0. 14.]]


# Урок 4

## Матрицы и матричные операции. Часть 2

### __1.__ Вычислить определитель:  

#### a) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$

 $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx\cdot sinx - (-cosx)\cdot cosx = sin^{2}x + cos^{2}x = 1$

#### б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 
4\cdot \begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 2\cdot \begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 3\cdot \begin{vmatrix} 
0 & 5 \\ 
0 & 0 
\end{vmatrix} = 4\cdot(5\cdot9-0\cdot1)-2\cdot(0\cdot9-0\cdot1)+3\cdot(0\cdot0-0\cdot5) = 4\cdot45 - 2\cdot0 + 3\cdot0 = 180$ 

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot5\cdot9 = 180$

In [23]:
import numpy as np

In [36]:
A = np.array([[4, 2, 3],
              [0, 5, 1], 
              [0, 0, 9]])
print(f'detA = {np.linalg.det(A)}')

detA = 180.0


#### в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2\cdot \begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3\cdot \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 1\cdot(5\cdot9-8\cdot6)-2\cdot(4\cdot9-7\cdot6)+3\cdot(4\cdot8-7\cdot5) 
= -3+12-9 = 0$

In [31]:
A = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])
print(f'detA = {np.linalg.det(A):.0f}')

detA = 0


### __2.__ Определитель матрицы $A$ равен $4$. Найти: 

#### а) $det(A^{2})$

Исходя из свойства $det(AB) = det(A)\cdot det(B)$ получаем:
$det(A^{2}) = det(A\cdot A) = det(A)\cdot det(A) =4\cdot4 = 16$

#### б) $det(A^{T})$

Исходя из свойства $det(A^{T})=det(A)=4$

#### в) $det(2A)$

Исходя из свойства определителей об умножении строки или столбца на число, для того чтобы дать ответ на этот вопрос необходимо знать размерность матрицы. Так как в таком случае на 2 умножаются все строки или столбцы и тогда определитель увеличится на 2 в степени равной колчеству строк или столбцов.

### __3.__  Доказать, что матрица вырожденная:
$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = -2\cdot \begin{pmatrix}
-14 & 6\\ 
7 & 13
\end{pmatrix} -7\cdot \begin{pmatrix} 
4 & 6\\ 
-3 & 13
\end{pmatrix} -3\cdot \begin{pmatrix} 
4 & -14\\ 
-3 & 7
\end{pmatrix}$ <br> $ = -2\cdot((-14)\cdot13-6\cdot7)-7\cdot(4\cdot13-(-3)\cdot6)-3\cdot(4\cdot7-(-3)\cdot(-14)) = 
-2\cdot(-182-42)-7\cdot(52+18)-3\cdot(27-42)) = -2\cdot(-224)-7\cdot(70)-3\cdot(-14)) 
= 448-490+42 = 0$

In [37]:
A = np.array([[-2, 7, -3],
              [4, -14, 6], 
              [-3, 7, 13]])
print(f'detA = {np.linalg.det(A):.0f}')

detA = 0


Определитель равен 0, следовательно матрица является вырожденной.

### __4.__ Найти ранг матрицы:

#### а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

3-я строка матрицы это 1-ая строка матрицы увеличенная на 1, следовательно эти строки линейно зависимы. Вторая строка не зависима. Значит матрица имеет ранг 2.

In [38]:
A = np.array([[1, 2, 3],
              [1, 1, 1], 
              [2, 3, 4]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2


#### б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

В данной матрице все строки являются линейно независимыми, следовательно матрица имеет ранг 3. 

In [40]:
A = np.array([[0, 0, 2, 1],
              [0, 0, 2, 2],
              [0, 0, 4, 3],
              [2, 3, 5, 6]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 3


### Функция нахождения определителя. 

Я приложила отдельный файл с тем, что успела сделать. Я смогла сделать функцию расчета определителя для матрицы 3х3. Я подготовила функцию для разложения любой матрицы до матриц 3х3 без испольования рекурсии. Но не успела придумать как хранить множители для этих матриц. Хотела сделать словарь, где в качестве ключа будет использована матрица преобразованная в строку, но потом поняла, что матрицы могут совпадать. И новый вариант найти не успела, к сожалению. 